### ISSUE TITLE
Failed tx on simple calling method <method_name> nonce undefined

### ISSUE THREAD

**Issue by mxevgenis** [hyperledger/caliper#869]
Hi everyone,
I am using caliper to measure several characteristics of my custom blockchain network by using the Smart contract i created. I have connected caliper with an Ethereum Quorum network where i have force to make transactions with zero cost. However i am using a custom Smart contract as it is presented below (described by a json file that contains the abi and bytecode):
pragma solidity >=0.4.22 <0.6.0;

contract simple {
    
   

  

    mapping (uint => string) public NetProvtoOwner;

    mapping (string => uint) OwnertoNetProv;

     mapping (string => bool) HasNetProv;

    
     mapping(string => uint) private accounts2;
   
    

    function addNetworkProvider(string memory name, uint id, uint id2 /*uint id3, uint id4*/) public{
        //uint id= NetworkProviders.push(NetworkProvider(name,offered_resources,reserved_resources,cost,domain,sla)) - 1 ;
        NetProvtoOwner[id] = name;
        OwnertoNetProv[name] = id;
        HasNetProv[name] = true;
        accounts2[name] = id2;
        // accounts3[name] = id3;
        // accounts4[name] = id4;
        //np_count +=1;
    }

}

I have configured the js file in order to utilize the above contract:

'use strict';

module.exports.info  = 'opening accounts';

let account_array = [];
let txnPerBatch;
let initMoney;
let bc, contx;
module.exports.init = function(blockchain, context, args) {
    if(!args.hasOwnProperty('money')) {
        return Promise.reject(new Error('simple.open - \'money\' is missed in the arguments'));
    }

    if(!args.hasOwnProperty('txnPerBatch')) {
        args.txnPerBatch = 2;
    }
    initMoney = args.money;
    txnPerBatch = args.txnPerBatch;
    bc = blockchain;
    contx = context;

    return Promise.resolve();
};

const dic = 'abcdefghijklmnopqrstuvwxyz';
/**
 * Generate string by picking characters from dic variable
 * @param {*} number character to select
 * @returns {String} string generated based on @param number
 */
function get26Num(number){
    let result = '';
    while(number > 0) {
        result += dic.charAt(number % 26);
        number = parseInt(number/26);
    }
    return result;
}

let prefix;
/**
 * Generate unique account key for the transaction
 * @returns {String} account key
 */
function generateAccount() {
    // should be [a-z]{1,9}
    if(typeof prefix === 'undefined') {
        prefix = get26Num(process.pid);
    }
    return prefix + get26Num(account_array.length+1);
}

/**
 * Generates simple workload
 * @returns {Object} array of json objects
 */
function generateWorkload() {
    let workload = [];
    for(let i= 0; i < txnPerBatch; i++) {
        let acc_id = generateAccount();
        account_array.push(acc_id);

        if (bc.getType() === 'fabric') {
            workload.push({
                chaincodeFunction: 'addNetworkProvider',
                chaincodeArguments: [acc_id, initMoney.toString()],
            });
        } else if (bc.getType() === 'ethereum') {
                workload.push({
                    verb: 'addNetworkProvider',
                    args: [acc_id, 10, 10]
                });
        } else {
            workload.push({
                'verb': 'addNetworkProvider',
                'account': acc_id,
                'money': initMoney
            });
        }
    }
    return workload;
}

module.exports.run = function() {
    let args = generateWorkload();
    return bc.invokeSmartContract(contx, 'simple', 'v0', args, 100);
};

module.exports.end = function() {
    return Promise.resolve();
};

module.exports.account_array = account_array;

When i run the benchmark i get the following error:

Failed tx on simple calling method addNetworkProvider nonce undefined

If i remove from the smart contract the 
accounts2[name] = id2;
it works.

Does caliper has some limitations regarding the amount of functions used by a js or the amount of factors a function uses?
In many other situation i also get the same error. Do you know what this error means?
Also does caliper supports the use of accounts?

**Comment by aklenik** [comment]
Still an issue

**Comment by mxevgenis** [comment]
I solved it when i deployed a newer version of Ethereum Quorum Network and i changed the value of nonce in the genesis file. I suppose caliper has versioning issues when it is connected to ethereum networks. Also it does not accept nonce = 0 value.

**Comment by aklenik** [comment]
@mxevgenis could you elaborate on your solution? What kind of settings made the error go away?

**Comment by mxevgenis** [comment]
I deployed 3 new Quorum nodes and i initialized the  network by changing in the genesis block the nonce value from 0 to  0x00000046. Then i executed  the benchmark successfully.  In my opinion the documentation of caliper needs to be updated and reformed. I faced many issues, and put a great effort in debugging in order to set up my experiment.

**Comment by aklenik** [comment]
@mxevgenis I absolutely agree with you, we're working on improving the documentation and providing tutorials. However, between improving the core code and documentation, we have little effort left to improve the DLT connectors and their documentation. 

We're constantly looking for DLT experts who can contribute to the connectors because the currently active maintainers are mainly Fabric experts. So any help is appreciated, feel free to reach out in the [caliper-contributors](https://chat.hyperledger.org/channel/caliper-contributors) Rocket.Chat channel if you have any ideas for improvement :)

**Comment by wvans123** [comment]
@mxevgenis  hello,i change the genesis nonce and refresh the quorum , but it can't work and have error message: BFT:invalid genesis block err="invalid nonce" how to deal it

**Comment by aklenik** [comment]
@wvans123 This seems like an ethereum-side error. First, make sure that the Ethereum nodes start without error. Then, if a benchmarking error still persists, open a new issue providing the details of the error.
